#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# This is provides the system startup/shutdown beeps 
#

# PROVIDE: beep
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="beep"

# Custom commands
start_cmd="beep_start"
stop_cmd="beep_stop"

beep_start()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O3L30cO4L30cO5L30cO5L30g > /dev/speaker
		fi
	fi
}

beep_stop()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O5L30gO5L30cO4L30cO3L30c > /dev/speaker
		fi
	fi
}

run_rc_command "$1"
