#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS CONFIG

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
