#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# Execute preinit commands
#

# PROVIDE: execcmd_preinit
# BEFORE: CONFIG
# REQUIRE: SYSTEMINIT rcconf

. /etc/rc.subr
. /etc/configxml.subr

if [ -x /etc/rc.d.php/preinit ]; then
	eval /etc/rc.d.php/preinit
fi

# Execute all commands.
/usr/local/bin/xml sel -t -m "//rc/preinit/cmd" \
	-v "." \
	-i "position() <= last()" -n -b \
	${configxml_file} | /usr/local/bin/xml unesc | \
	while read _cmd; do
		eval ${_cmd}
	done

# Execute all commands from config 2.8.
/usr/local/bin/xml sel -t -m "//rc/param[typeid=1 and enable]/value" \
	-v "." \
	-i "position() <= last()" -n -b \
	${configxml_file} | /usr/local/bin/xml unesc | \
	while read _cmd; do
		eval ${_cmd}
	done
