#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# hostname
#
# XigmaNAS® Checked: stable/14 /libexec/rc/rc.d/hostname		943ad2ce59887a63182e5e26ea6962e978ac59bd
#
# Set system hostname
#

# PROVIDE: hostname
# REQUIRE: FILESYSTEMS
# BEFORE:  netif

. /etc/rc.subr
. /etc/network.subr

name="hostname"
desc="Set the system\'s hostname"
start_cmd="hostname_start"
restart_cmd="hostname_restart"
stop_cmd=":"

hostname_start()
{
	# If we are not inside a jail, set the host name.
	# If we are inside a jail, set the host name if it is permitted.
	#
	if check_jail jailed; then
		if ! check_jail set_hostname_allowed; then
			return
		fi
	else
		# If we're not in a jail and rc.conf doesn't specify a
		# hostname, see if we can get one from kenv.
		#
		if [ -z "${hostname}" -a \
		    -n "`/bin/kenv dhcp.host-name 2> /dev/null`" ]; then
			hostname=`/bin/kenv dhcp.host-name`
		fi
	fi

	# Have we got a hostname yet?
	#
	if [ -z "${hostname}" ]; then
		# Null hostname is probably OK if DHCP is in use,
		# or when hostname is already set (common for jails).
		#
		if [ -z "`list_net_interfaces dhcp`" -a \
		     -z "`/bin/hostname`" ]; then
			warn "\$hostname is not set -- see rc.conf(5)."
		fi
		return
	fi

	# All right, it is safe to invoke hostname(1) now.
	#
	startmsg -n "Setting hostname: ${hostname}"
	/bin/hostname "${hostname}"
	startmsg '.'
}

hostname_restart()
{
	# Reset hostname
	/bin/hostname ""
	run_rc_command start
}

load_rc_config $name
run_rc_command "$1"
