#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# Generating .htpasswd
#

# PROVIDE: htpasswd
# REQUIRE: cleanvar

. /etc/rc.subr
. /etc/configxml.subr

# Defaults
htpasswd=${htpasswd:-"/var/run/.htpasswd"}

echo "Generating .htpasswd."

# Encrypt password
_password=`configxml_get "//system/password"`
_password_md5=`/usr/sbin/mkpw -e md5 "${_password}"`
_password_sha=`configxml_get "//system/password"`

# Generate the /var/run/.htpasswd file used by lighttpd
/usr/local/bin/xml sel -t \
	-i "string-length(//system/username) > 0" -v //system/username -b \
	-i "string-length(//system/username) = 0" -o "admin" -b \
	-o ":${_password_sha}" \
	${configxml_file} | /usr/local/bin/xml unesc > ${htpasswd}

/bin/chmod 0600 ${htpasswd}
