#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# Mount critical remote filesystems
#
# XigmaNAS® Checked: 13.1/libexec/rc/rc.d/mountcritremote		commit 31b29217a
# XigmaNAS® Changes: - Modify prereq's and remove REQUIRE: ipsec
#

# PROVIDE: mountcritremote
# REQUIRE: NETWORKING FILESYSTEMS ipsec netwait nfscbd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="mountcritremote"
desc="Mount critical remote file systems"
stop_cmd="mountcritremote_stop"
start_cmd="mountcritremote_start"
start_precmd="mountcritremote_precmd"

# Mount NFS filesystems if present in /etc/fstab
#
# XXX When the vfsload() issues with nfsclient support and related sysctls
# have been resolved, this block can be removed, and the condition that
# skips nfs in the following block (for "other network filesystems") can
# be removed.
#
mountcritremote_precmd()
{
	# Currently this script is used as dummy.
	return 0
}

mountcritremote_start()
{
	local _result

	eval "/etc/rc.d.php/${name} cmd=start"
	_result=$?

	return ${_result}
}

mountcritremote_stop()
{
	local _result

	eval "/etc/rc.d.php/${name} cmd=stop"
	_result=$?

	return ${_result}
}

load_rc_config $name
run_rc_command "$1"
