#!/bin/sh
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
# Configure htpasswd
#

# PROVIDE: websrv_htpasswd
# REQUIRE: userdb DAEMON
# XQUERY: --if 'count(//websrv/enable) > 0 and count(//websrv/authentication/enable) > 0' --output '0' --break
# RCVAR: websrv_htpasswd

. /etc/rc.subr
. /etc/configxml.subr

if configxml_isset //websrv/enable; then
#	calculate defaults
	documentroot=`configxml_get "//websrv/documentroot"`
	htpasswdfile=".websrv_htpasswd"
	htpasswd="${documentroot}/${htpasswdfile}"
#	wipe or generate the htpasswd file used by websrv and apply owner and permissions.
	echo "Generating ${htpasswdfile}."
	/bin/cat /dev/null > "${htpasswd}"
	/bin/chmod 0600 "${htpasswd}"
	/usr/sbin/chown www:www "${htpasswd}"
#	process configured users when authentication is enabled
	if configxml_isset //websrv/authentication/enable; then
		/usr/local/bin/xml sel --template \
			--match "//access/user[enable]" \
				--if 'string-length(login) > 0' \
					--if 'string-length(passwordsha) > 0' \
						--value-of 'concat(login,":",passwordsha)' --nl \
					--else \
						--value-of 'concat(login,":*")' --nl \
					--break \
				--break \
			--break \
			${configxml_file} | /usr/local/bin/xml unesc >> "${htpasswd}"
	fi
fi
