etc/inc/XMLRPC
etc/rc.beupgrade
usr/local/etc/php/ext-20-intl.ini
usr/local/lib/samba/libldb.so.1
usr/local/www/diag_infos.php
usr/local/www/diag_infos_ata.php
usr/local/www/diag_infos_disksinfo.php
usr/local/www/graph.php
usr/local/www/graph_cpu.php
usr/local/www/status_report.php
usr/local/www/system_rrdgraphs.php
usr/local/www/xmlrpc.php
usr/local/www/images/navbar_active.png
usr/local/www/images/navbar_default.png
etc/install/include/boot/menu.4th
etc/install/include/boot
# 6536
etc/inc/properties_services_ctl.php
etc/inc/properties_services_ctl_auth_group.php
etc/inc/properties_services_ctl_lun.php
etc/inc/properties_services_ctl_portal_group.php
etc/inc/properties_services_ctl_sub_chap.php
etc/inc/properties_services_ctl_sub_chap_mutual.php
etc/inc/properties_services_ctl_sub_initiator_name.php
etc/inc/properties_services_ctl_sub_initiator_portal.php
etc/inc/properties_services_ctl_sub_isnsserver.php
etc/inc/properties_services_ctl_sub_listen.php
etc/inc/properties_services_ctl_sub_lun.php
etc/inc/properties_services_ctl_sub_option.php
etc/inc/properties_services_ctl_sub_port.php
etc/inc/properties_services_ctl_target.php
etc/inc/properties_services_mariadb.php
etc/inc/properties_syslogconf.php
# 6570
etc/inc/properties_smartmontoold_umass.php
# 6575
etc/inc/properties_iscsi_initiator.php
# 6601
etc/inc/properties_services_tftp.php
# 6632
usr/local/www/services_nfs_share.php
usr/local/www/services_nfs_share_edit.php
# 6651
etc/inc/properties_access_users.php
# 6767
usr/local/libexec/in.tftpd
# 6942
etc/inc/properties_services_samba_share.php
etc/inc/properties_services_samba_share_edit.php
# 7010
etc/inc/properties_sysctl.php
# 7178
etc/inc/properties_services_websrv_webdav.php
# 7202
etc/inc/properties_system_backup.php
# 7236
etc/inc/properties_disks_zfs_settings.php
# 7278
usr/local/www/access_users_groups.php
usr/local/www/access_users_groups_edit.php
# 7331
usr/local/www/quixplorer/_lang/af_mimes.php
usr/local/www/quixplorer/_lang/bg_mimes.php
usr/local/www/quixplorer/_lang/ca_mimes.php
usr/local/www/quixplorer/_lang/cs_mimes.php
usr/local/www/quixplorer/_lang/da_mimes.php
usr/local/www/quixplorer/_lang/de_mimes.php
usr/local/www/quixplorer/_lang/el_mimes.php
usr/local/www/quixplorer/_lang/en_US_mimes.php
usr/local/www/quixplorer/_lang/es_mimes.php
usr/local/www/quixplorer/_lang/fi_mimes.php
usr/local/www/quixplorer/_lang/fr_mimes.php
usr/local/www/quixplorer/_lang/hu_mimes.php
usr/local/www/quixplorer/_lang/it_mimes.php
usr/local/www/quixplorer/_lang/ja_mimes.php
usr/local/www/quixplorer/_lang/ko_mimes.php
usr/local/www/quixplorer/_lang/nb_mimes.php
usr/local/www/quixplorer/_lang/nl_mimes.php
usr/local/www/quixplorer/_lang/pl_mimes.php
usr/local/www/quixplorer/_lang/pt_mimes.php
usr/local/www/quixplorer/_lang/pt_BR_mimes.php
usr/local/www/quixplorer/_lang/ro_mimes.php
usr/local/www/quixplorer/_lang/ru_mimes.php
usr/local/www/quixplorer/_lang/sk_mimes.php
usr/local/www/quixplorer/_lang/sv_mimes.php
usr/local/www/quixplorer/_lang/sl_mimes.php
usr/local/www/quixplorer/_lang/tr_mimes.php
usr/local/www/quixplorer/_lang/uk_mimes.php
usr/local/www/quixplorer/_lang/zh_CN_mimes.php
usr/local/www/quixplorer/_lang/zh_TW_mimes.php
# 7455
usr/local/www/quixplorer/_include/js_admin.php
usr/local/www/quixplorer/_include/js_admin2.php
usr/local/www/quixplorer/_include/js_admin3.php
usr/local/www/quixplorer/_include/admin.php
usr/local/www/quixplorer/_include/edit.php
usr/local/www/quixplorer/_lang/_info.php
usr/local/www/quixplorer/_lang/af.php
usr/local/www/quixplorer/_lang/bg.php
usr/local/www/quixplorer/_lang/ca.php
usr/local/www/quixplorer/_lang/cs.php
usr/local/www/quixplorer/_lang/da.php
usr/local/www/quixplorer/_lang/de.php
usr/local/www/quixplorer/_lang/el.php
usr/local/www/quixplorer/_lang/en_US.php
usr/local/www/quixplorer/_lang/es.php
usr/local/www/quixplorer/_lang/fi.php
usr/local/www/quixplorer/_lang/fr.php
usr/local/www/quixplorer/_lang/hu.php
usr/local/www/quixplorer/_lang/it.php
usr/local/www/quixplorer/_lang/ja.php
usr/local/www/quixplorer/_lang/ko.php
usr/local/www/quixplorer/_lang/nb.php
usr/local/www/quixplorer/_lang/nl.php
usr/local/www/quixplorer/_lang/pl.php
usr/local/www/quixplorer/_lang/pt.php
usr/local/www/quixplorer/_lang/pt_BR.php
usr/local/www/quixplorer/_lang/ro.php
usr/local/www/quixplorer/_lang/ru.php
usr/local/www/quixplorer/_lang/sk.php
usr/local/www/quixplorer/_lang/sv.php
usr/local/www/quixplorer/_lang/sl.php
usr/local/www/quixplorer/_lang/tr.php
usr/local/www/quixplorer/_lang/uk.php
usr/local/www/quixplorer/_lang/zh_CN.php
usr/local/www/quixplorer/_lang/zh_TW.php
# 7502
usr/local/www/quixplorer
etc/rc.d/fmperm
# 7532
usr/local/sbin/beadm
# 8277
usr/local/www/services_dynamicdns.php
# 8293
usr/local/bin/python3.6
usr/local/lib/libpython3.6m.so.1.0
# 8690
etc/inc/properties_diag_log_settings.php
# 8741
usr/local/www/status_graph_tabs.inc
# 8847/8854
etc/ssh/ssh_host_dsa_key
etc/ssh/ssh_host_rsa_key
# 9066
etc/inc/fm_archive.php
etc/inc/fm_chmod.php
etc/inc/fm_conf.php
etc/inc/fm_configs.php
etc/inc/fm_copy_move.php
etc/inc/fm_debug.php
etc/inc/fm_del.php
etc/inc/fm_down.php
etc/inc/fm_edit_editarea.php
etc/inc/fm_error.php
etc/inc/fm_extra.php
etc/inc/fm_footer.php
etc/inc/fm_header.php
etc/inc/fm_init.php
etc/inc/fm_javascript.php
etc/inc/fm_lib_PEAR.php
etc/inc/fm_lib_Tar.php
etc/inc/fm_lib_archive.php
etc/inc/fm_lib_file.php
etc/inc/fm_lib_folder.php
etc/inc/fm_lib_path.php
etc/inc/fm_lib_zipstream.php
etc/inc/fm_list.php
etc/inc/fm_login.php
etc/inc/fm_mimes.php
etc/inc/fm_mkitem.php
etc/inc/fm_permissions.php
etc/inc/fm_qx.php
etc/inc/fm_qxpage.php
etc/inc/fm_qxpath.php
etc/inc/fm_search.php
etc/inc/fm_session.php
etc/inc/fm_str.php
etc/inc/fm_unzip.php
etc/inc/fm_user.php
# 9463
usr/local/lib/php/extensions/no-debug-non-zts-20210902/apcu.so
usr/local/lib/php/extensions/no-debug-non-zts-20210902/opcache.so
usr/local/lib/php/extensions/no-debug-non-zts-20210902
# 9566
usr/local/www/images/announcement12.gif
usr/local/www/images/header_bg.png
usr/local/www/images/header_logo.png
usr/local/www/images/header_rlogo.png
# 9763
usr/local/www/css/fm_style.css
usr/local/www/css/fm_style.css.php
usr/local/www/css/login.css
usr/local/www/css/login.css.php
# 9773
usr/local/www/css/navbar-full-no-lev1.css
usr/local/www/css/navbar-until-2022-12-31.css
# 10024
usr/local/lib/python3.9
usr/local/lib/libpython3.9.so.1
usr/local/lib/libpython3.9.so.1.0
# 10024
lib/casper
sbin/iscontrol
usr/libexec/make_index
usr/sbin/ancontrol
usr/sbin/portsnap
# 10243
usr/libexec/sftp-server
usr/libexec/sshd-session
# 10269
usr/local/www/services_fuppes.php
# 10366
usr/local/lib/libupsclient.so.6
# 10520
boot/modules/vboxguest.ko
usr/local/sbin/VBoxControl
usr/local/sbin/VBoxService
# 10566
usr/local/lib/samba
usr/local/lib/libdcerpc.so.0
usr/local/lib/libdcerpc-binding.so.0
usr/local/lib/libdcerpc-samr.so.0
usr/local/lib/libdcerpc-server.so.0
usr/local/lib/libdcerpc-server-core.so.0
usr/local/lib/libndr.so.4
usr/local/lib/libndr-krb5pac.so.0
usr/local/lib/libndr-nbt.so.0
usr/local/lib/libndr-standard.so.0
usr/local/lib/libnetapi.so.1
usr/local/lib/libsamba-credentials.so.1
usr/local/lib/libsamba-errors.so.1
usr/local/lib/libsamba-hostconfig.so.0
usr/local/lib/libsamba-passdb.so.0
usr/local/lib/libsamba-policy.cpython-311.so.0
usr/local/lib/libsamba-util.so.0
usr/local/lib/libsamdb.so.0
usr/local/lib/libsmbclient.so.0
usr/local/lib/libsmbconf.so.0
usr/local/lib/libsmbldap.so.2
usr/local/lib/libtevent-util.so.0
usr/local/lib/libwbclient.so.0
