#!/usr/local/bin/php-cgi -f
<?php
/*
	mountcritremote - script to mount iscsi-based configured filesystems

	Part of XigmaNAS® (https://www.xigmanas.com).
	Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
	All rights reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice, this
	   list of conditions and the following disclaimer.

	2. Redistributions in binary form must reproduce the above copyright notice,
	   this list of conditions and the following disclaimer in the documentation
	   and/or other materials provided with the distribution.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
	ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
	ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

	The views and conclusions contained in the software and documentation are those
	of the authors and should not be interpreted as representing official policies
	of XigmaNAS®, either expressed or implied.
*/

require_once 'autoload.php';
require_once 'config.inc';
require_once 'functions.inc';

use common\arr;

if(!isset($_GET['cmd']) || empty($_GET['cmd'])):
	return -1;
endif;
$cfg_mounts = arr::make_branch($config,'mounts','mount');
if(empty($cfg_mounts)):
	return -1;
endif;
//	mount/umount iSCSI disks
$iscsi = @exec('/sbin/sysctl -q -n net.iscsi_initiator.driver_version');
switch($_GET['cmd']):
	case 'start':
//		XXX iscsi loaded
		if(!empty($iscsi)):
			sleep(1);
		endif;
//		XXX should take iscsi only
//		disks_mount_all();
		foreach($cfg_mounts as $mount):
//			skip mounted entry
			if(disks_ismounted($mount)):
				continue;
			endif;
			disks_mount($mount);
		endforeach;
		break;
	case 'stop':
		$a_disks = get_iscsi_disks_list();
		foreach($a_disks as $diskv):
			$mdisk = $diskv["devicespecialfile"];
			$index = arr::search_ex($mdisk,$cfg_mounts,'mdisk');
			if($index !== false):
				$mount = $cfg_mounts[$index];
				if(disks_ismounted($mount)):
					$dev = $mount['devicespecialfile'];
					system('/bin/sync');
					system("/sbin/umount $dev");
				endif;
			endif;
		endforeach;
		if(!empty($iscsi)):
			sleep(1);
		endif;
		break;
endswitch;
return 0;
