#!/usr/local/bin/php-cgi -f
<?php
#
# Part of XigmaNAS® (https://www.xigmanas.com).
# Copyright © 2018-2025 XigmaNAS® <info@xigmanas.com>.
# All rights reserved.
#
require_once 'report.inc';

$retval = @report_send_mail();
exit($retval);
?>
